name: select_text_field
version: 0.0.4
description: SelectTextField is a Flutter package that provides a customizable text field widget with a dropdown icon. It allows users to select options from a modal bottom sheet, providing a convenient and intuitive user interface for selecting values.
homepage: https://github.com/aro-wolo/select_text_field

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  tinycolor2: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true