name: select_text_field
version: 1.0.1
description: SelectTextField is a Flutter package that provides a customizable text field widget with a dropdown icon. It allows users to select options from a modal bottom sheet, providing a convenient and intuitive user interface for selecting values.


environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  tinycolor2: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true  

